# Generated by Django 2.2.10 on 2020-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=150, verbose_name='user_id')),
                ('sessionId', models.CharField(max_length=150, verbose_name='session_id')),
                ('actionTime', models.DateTimeField(verbose_name='action_time')),
                ('actionType', models.CharField(max_length=150, verbose_name='action_type')),
                ('actionProperties', models.TextField(max_length=250, verbose_name='action_properties')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
